### ISSUE TITLE
Getting this error with the raft branch on RethinkDB 2.1

### ISSUE THREAD

**Issue by thelinuxlich** [neumino/rethinkdbdash#127]
```
The changefeed on server_status returned an error: ReqlServerError: The connection was closed before the query could be completed for:
Aug 11 19:16:48 aidax-batcher-1 aidax[2580]: r.db("rethinkdb").table("server_status").union(["feedSeparator"]).union(r.db("rethinkdb").table("server_status").changes())
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: Unhandled rejection TypeError: Cannot read property 'reject' of undefined
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at /app/releases/20150811164745/node_modules/rethinkdbdash/lib/connection.js:533:25
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at Object.tryCatch (/app/releases/20150811164745/node_modules/rethinkdbdash/lib/helper.js:170:3)
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at Connection._send (/app/releases/20150811164745/node_modules/rethinkdbdash/lib/connection.js:530:10)
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at /app/releases/20150811164745/node_modules/rethinkdbdash/lib/term.js:199:32
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at tryCatcher (/app/releases/20150811164745/node_modules/bluebird/js/main/util.js:26:23)
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at Promise._settlePromiseFromHandler (/app/releases/20150811164745/node_modules/bluebird/js/main/promise.js:503:31)
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at Promise._settlePromiseAt (/app/releases/20150811164745/node_modules/bluebird/js/main/promise.js:577:18)
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at Promise._settlePromiseAtPostResolution (/app/releases/20150811164745/node_modules/bluebird/js/main/promise.js:244:10)
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at Async._drainQueue (/app/releases/20150811164745/node_modules/bluebird/js/main/async.js:128:12)
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at Async._drainQueues (/app/releases/20150811164745/node_modules/bluebird/js/main/async.js:133:10)
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at Immediate.Async.drainQueues [as _onImmediate] (/app/releases/20150811164745/node_modules/bluebird/js/main/async.js:15:14)
Aug 11 19:17:25 aidax-batcher-1 aidax[2580]: at processImmediate [as _immediateCallback] (timers.js:368:17)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: Unhandled rejection TypeError: Cannot read property 'reject' of undefined
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at /app/releases/20150811164745/node_modules/rethinkdbdash/lib/connection.js:533:25
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at Object.tryCatch (/app/releases/20150811164745/node_modules/rethinkdbdash/lib/helper.js:170:3)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at Connection._send (/app/releases/20150811164745/node_modules/rethinkdbdash/lib/connection.js:530:10)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at /app/releases/20150811164745/node_modules/rethinkdbdash/lib/term.js:199:32
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at tryCatcher (/app/releases/20150811164745/node_modules/bluebird/js/main/util.js:26:23)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at Promise._settlePromiseFromHandler (/app/releases/20150811164745/node_modules/bluebird/js/main/promise.js:503:31)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at Promise._settlePromiseAt (/app/releases/20150811164745/node_modules/bluebird/js/main/promise.js:577:18)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at Promise._settlePromiseAtPostResolution (/app/releases/20150811164745/node_modules/bluebird/js/main/promise.js:244:10)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at Async._drainQueue (/app/releases/20150811164745/node_modules/bluebird/js/main/async.js:128:12)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at Async._drainQueues (/app/releases/20150811164745/node_modules/bluebird/js/main/async.js:133:10)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at Immediate.Async.drainQueues [as _onImmediate] (/app/releases/20150811164745/node_modules/bluebird/js/main/async.js:15:14)
Aug 11 19:18:07 aidax-batcher-1 aidax[2580]: at processImmediate [as _immediateCallback] (timers.js:368:17)
```

**Comment by neumino** [comment]
The message was just printed right?
This is expected if the connection to the server where the feeds is opened dies.
