### ISSUE TITLE
Error: write after end    events.js: 141

### ISSUE THREAD

**Issue by Balleraza** [neumino/rethinkdbdash#160]
We're using rethinkdbdash and we think it's awesome - the connection pooling is solving a lot of our issues.  However, we've run into this problem that I can't reproduce consistently, but I felt like I should let you know about: 

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:159:12)
    at TLSSocket.Writable.write (_stream_writable.js:204:5)
    at TLSSocket.Socket.write (net.js:616:40)
    at /opt/clientsuccess/node_modules/rethinkdbdash/lib/connection.js:104:23
    at Object.tryCatch (/opt/clientsuccess/node_modules/rethinkdbdash/lib/helper.js:167:3)
    at TLSSocket.<anonymous> (/opt/clientsuccess/node_modules/rethinkdbdash/lib/connection.js:103:12)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1033:10)
```

**Comment by neumino** [comment]
Thanks @Balleraza for the report.

Do you just get the stacktrace printed? Or does your node process actually crashes?

**Comment by Balleraza** [comment]
The node process crashes but we run a docker script that starts it up again the moment it does crash.  However it prevents our service from being able to finish what it was doing (in this case emailing an alert to a client).

**Comment by neumino** [comment]
I believed it should be fixed with 2.1.10.

We were emitting an error a bit too early (before the pool actually has a change to bind a listener). If you still see this crash with 2.1.10, could you reopen the issue (and provide the backtrace if not the same).
Thanks!

**Comment by Balleraza** [comment]
Now I get this: ```events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1042:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:889:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickDomainCallback (node.js:385:17)
    at process.wrappedFunction (/opt/clientsuccess/node_modules/newrelic/lib/transaction/tracer/index.js:271:51)```

**Comment by neumino** [comment]
Isn't that an issue with Newrelic?

**Comment by Balleraza** [comment]
Yes, sorry my mistake
