### ISSUE TITLE
Bluebird 3 Issue

### ISSUE THREAD

**Issue by artdude543** [neumino/rethinkdbdash#171]
Installed 2.1.14 via git to try out the "fix" for Bluebird 3 but having a new error thrown other than the one I had here. neumino/thinky#378

```
Warning: a promise was created in a handler but none were returned from it
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Pool.createConnection (~\node_modules\rethinkdbdash\lib\pool.js:197:51)
    at null._onTimeout (~\node_modules\rethinkdbdash\lib\pool.js:53:14)
    at Timer.listOnTimeout (timers.js:92:15)
```

Using Bluebird `3.0.3`

**Comment by neumino** [comment]
This is a thinky issue, not a rethinkdbdash issue.
Let's talk about it there.
