### ISSUE TITLE
With DB down, infinite retries

### ISSUE THREAD

**Issue by cyounkins** [neumino/rethinkdbdash#173]
When the database is down, an attempt to connect seems to result in an infinite retry loop without ability to cancel.

Example:
```
var rdbdash = require('rethinkdbdash');
var r = rdbdash({
    discovery: true,
    pool: true,
    buffer: 1,
    max: 10,
    servers: [
        { host: 'localhost', port: 28015, db: 'test' }
    ]
});
```

It looks like Pool.createConnection calls itself: https://github.com/neumino/rethinkdbdash/blob/master/lib/pool.js#L292

It should stop if the pool is set to drain, but calling ```.getPoolMaster().drain();``` does not work, throwing:

```
Unhandled rejection TypeError: Cannot call method 'close' of null
    at PoolMaster.drain (/var/local/purge-log-db/node_modules/rethinkdbdash/lib/pool_master.js:498:16)
    at /var/local/purge-log-db/src/index.js:48:23
    at tryCatcher (/var/local/purge-log-db/node_modules/rethinkdbdash/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/var/local/purge-log-db/node_modules/rethinkdbdash/node_modules/bluebird/js/main/catch_filter.js:52:40)
    at CatchFilter.tryCatcher (/var/local/purge-log-db/node_modules/rethinkdbdash/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/local/purge-log-db/node_modules/rethinkdbdash/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/var/local/purge-log-db/node_modules/rethinkdbdash/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/var/local/purge-log-db/node_modules/rethinkdbdash/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/var/local/purge-log-db/node_modules/rethinkdbdash/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/local/purge-log-db/node_modules/rethinkdbdash/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/var/local/purge-log-db/node_modules/rethinkdbdash/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
```

Link to near error: https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L494

Any known workaround? Thanks!

**Comment by neumino** [comment]
Infinite retries are expected, the crash was fixed in 2.1.15
