### ISSUE TITLE
Warning: a promise was created in a  handler but was not returned from it

### ISSUE THREAD

**Issue by roblav96** [neumino/rethinkdbdash#179]
I'm constantly getting this warning:
```
c-0  Warning: a promise was created in a  handler but was not returned from it
c-0     at Term.run (/Users/roblav96/Projects/app/server/node_modules/rethinkdbdash/lib/term.js:145:21)
c-0     at /Users/roblav96/Projects/app/server/src/routes/public/register.js:41:36
c-0 From previous event:
c-0     at Server.module.exports (/Users/roblav96/Projects/app/server/src/routes/public/register.js:16:45)
c-0     at next (/Users/roblav96/Projects/app/server/node_modules/restify/lib/server.js:906:30)
c-0     at f (/Users/roblav96/Projects/app/server/node_modules/once/once.js:17:25)
c-0     at /Users/roblav96/Projects/app/server/src/middle/public/verify-initKey.js:24:4
c-0     at bound (domain.js:280:14)
c-0     at runBound (domain.js:293:12)
c-0 From previous event:
c-0     at /Users/roblav96/Projects/app/server/src/middle/public/verify-initKey.js:22:88
c-0     at bound (domain.js:280:14)
c-0     at runBound (domain.js:293:12)
c-0     at tryCatcher (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)
c-0     at Promise._settlePromiseFromHandler (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:507:31)
c-0     at Promise._settlePromiseAt (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:581:18)
c-0     at Promise._settlePromises (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:697:14)
c-0     at Async._drainQueue (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)
c-0     at Async._drainQueues (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)
c-0     at Immediate.Async.drainQueues [as _onImmediate] (/Users/roblav96/Projects/app/server/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)
c-0     at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I've already looked into the warning docs in the API. I tried returning null, but nothing works.

**Comment by roblav96** [comment]
I ended up just hiding warnings with
```
BLUEBIRD_WARNINGS=0
```
There must be a reason that the developer put that warning in there though.

**Comment by roblav96** [comment]
I hope you don't just return null on everything because that's the wrong way of doing it...

If the other promise is rejected, this will happen unnoticed instead of being propagated to the new promise (where it would get handled) - and the new promise stays forever pending, **which can induce leaks.**

**Comment by roblav96** [comment]
Actually, if it works it works. lol

**Comment by neumino** [comment]
Can you provide a script that trigger this warning? I can't get to reproduce it.

It's also safe to return `null`. It can leaks if you don't bind an error listener and such, but we do.

**Comment by roblav96** [comment]
It seems to happen when I run a query inside another query promise like so:
```
module.exports = function ( req, res, next ) {
	r.table( 'users' ).get( req.xid ).run().then( function ( doc ) {
		doc.stamp = _.now()
		r.table( 'users' ).get( req.xid ).update( doc ).run().then( function () {
			return res.send( true )
		} ).error( function ( err ) {
			console.error( err )
			return res.send( 500 )
		} )
	} ).error( function ( err ) {
		console.error( err )
		return res.send( 500 )
	} )
}
```
That will reproduce the warning. Let me know if there's anything else I can do. Thank you!

**Comment by neumino** [comment]
Well, the warning is being triggered by your code, not rethinkdbdash. You can:
- return null in the first handler
- properly chain your promises

IMO, your code should be:
```
module.exports = function ( req, res, next ) {
    r.table( 'users' ).get( req.xid ).run().then( function ( doc ) {
        doc.stamp = _.now()
        return r.table( 'users' ).get( req.xid ).update( doc ).run();
    }).then( function () {
        return res.send( true )
    } ).error( function ( err ) {
        console.error( err )
        return res.send( 500 )
    } )
}
```

**Comment by roblav96** [comment]
Interesting. lol I was unaware you could do that. Thank you!

**Comment by primitive-type** [comment]
@neumino I get this warning when I start my app up, but **only** if I set the `discovery` option to `true` when importing thinky. This is the only thing that affects whether I see the warning or not. I literally went through every possibly guilty part of my app, commenting out code and testing, and nothing else made a difference. But simply changing that option determines whether the warning appears on startup. Additionally, this seems to only happen when running my app within a Docker container, but I haven't confirmed that yet.

**Comment by primitive-type** [comment]
In my case, all of the stack traces point to rethinkdbdash code (again, only when `discovery` option is set to `true`):

```
Warning: a promise was created in a  handler but was not returned from it
    at Cursor._next (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:52:11)
    at Cursor._each (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:239:8)
    at /usr/src/app/node_modules/rethinkdbdash/lib/pool_master.js:301:10
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at PoolMaster.fetchServers (/usr/src/app/node_modules/rethinkdbdash/lib/pool_master.js:293:11)
    at null._onTimeout (/usr/src/app/node_modules/rethinkdbdash/lib/pool_master.js:73:50)
    at Timer.listOnTimeout (timers.js:92:15)

Warning: a promise was created in a  handler but was not returned from it
    at Cursor._fetch (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:114:11)
    at Cursor._push (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:135:86)
    at /usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:117:10
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Cursor._fetch (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:116:6)
    at Cursor._push (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:135:86)
    at Connection._processResponse (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:391:14)
    at Socket.<anonymous> (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:150:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Warning: a promise was created in a  handler but was not returned from it
    at Cursor._fetch (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:114:11)
From previous event:
    at Cursor._fetch (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:116:6)
    at Cursor._push (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:135:86)
    at Connection._processResponse (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:391:14)
    at Socket.<anonymous> (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:150:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
What exactly is `discovery` mode supposed to be doing? When should it be used?

**Comment by neumino** [comment]
@primitive-type -- Can you provide a script that triggers these warnings? Importing thinky with `discovery: true` works fine for me.

**Comment by neumino** [comment]
Also how many servers do you have in your cluster?

**Comment by roblav96** [comment]
Maybe try updating bluebird? They might've released a bug fix. Idk

**Comment by primitive-type** [comment]
Just starting up my app triggers the warnings. One detail I forgot to mention is that this issue only occurs when running my app inside Docker (both locally and when deployed). It doesn't happen when I run it on my local machine outside of Docker.

Also, Bluebird is not a dependency of my app, except indirectly through thinky. So I can't update Bluebird, since none of my actual code uses it (except indirectly). 

I will try to produce a minimal script that triggers these warnings, but I suspect the culprit has something to do with a combination of `discovery` mode and Docker. Since I'm not too familiar with Docker, it may take me a while to get a separate example app running with Docker to reproduce this issue.

**Comment by primitive-type** [comment]
The following script triggers the warning for me, when run inside Docker on my local machine:

```javascript
var Hapi = require('hapi');

var thinky = require('thinky')({
    discovery: true,
    db: 'local',
    host: 'rethinkdb'
});

var server = new Hapi.Server();

server.connection({
    port: 80,
    host: '0.0.0.0'
});

server.start(function(err) {
    if (err) {
        console.log('ERROR: ', err.message);
    }
});
```
The output I get in the console is the following:

```
Creating a pool connected to rethinkdb:28015
Warning: a promise was created in a  handler but was not returned from it
    at Cursor._next (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:52:11)
    at Cursor._each (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:239:8)
    at /usr/src/app/node_modules/rethinkdbdash/lib/pool_master.js:301:10
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at PoolMaster.fetchServers (/usr/src/app/node_modules/rethinkdbdash/lib/pool_master.js:293:11)
    at null._onTimeout (/usr/src/app/node_modules/rethinkdbdash/lib/pool_master.js:73:50)
    at Timer.listOnTimeout (timers.js:92:15)

Warning: a promise was created in a  handler but was not returned from it
    at Cursor._fetch (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:114:11)
    at Cursor._push (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:135:86)
    at /usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:117:10
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Cursor._fetch (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:116:6)
    at Cursor._push (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:135:86)
    at Connection._processResponse (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:391:14)
    at Socket.<anonymous> (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:150:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Warning: a promise was created in a  handler but was not returned from it
    at Cursor._fetch (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:114:11)
From previous event:
    at Cursor._fetch (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:116:6)
    at Cursor._push (/usr/src/app/node_modules/rethinkdbdash/lib/cursor.js:135:86)
    at Connection._processResponse (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:391:14)
    at Socket.<anonymous> (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:150:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Creating a pool connected to 172.17.0.3:28015
Removing pool connected to: rethinkdb:28015
Draining the pool connected to rethinkdb:28015
```

If it's relevant, here is the `docker-compose.yml` file I am using to build the container:

```yml
codecontainer:
  image: busybox
  volumes:
    - ./:/usr/src/app


keyfilecontainer:
  image: busybox
  volumes:
    - ./:/var/run/secrets/gcloud

dexterapi:
  build: .
  working_dir: /usr/src/app
  command: /bin/sh -c "while true; do sleep 1; done"
  ports:
    - 80:80
  environment:
    - NODE_ENV=development
    - REDIS_SERVICE_HOST=redis
  links:
    - rethinkdb:rethinkdb
    - redis:redis
  volumes:
    - ./:/var/run/secrets/dexter
  volumes_from:
    - codecontainer
    - keyfilecontainer

rethinkdb:
  image: rethinkdb:2.1.5
  volumes:
    - ./:/data
  ports:
    - 8080:8080
    - 28015:28015
  expose:
    - 28015
    - 80
redis:
    image: redis
```

My version of thinky is 2.1.12 and my version of hapi is 11.1.2. As seen in the `docker-compose.yml` file, the version of RethinkDB is 2.1.5.

**Comment by neumino** [comment]
What version of rethinkdbdash is thinky using?

**Comment by neumino** [comment]
You need at least 2.1.17 (or pin bluebird's version to 2.0

**Comment by primitive-type** [comment]
It appears that thinky is using rethinkdbdash 2.1.17, which in turn requires bluebird version `">= 3.0.1"` according to its `package.json` file. Since I am not requiring these dependencies directly in my app, is it safe to alter thinky's and / or rethinkdbdash's `package.json` and fiddle with their dependency versions?

**Comment by neumino** [comment]
@primitive-type -- add a `return null` at the end of `Cursor.prototype._each` in `lib/cursor.js`. I believe this is where your problem comes from.

**Comment by neumino** [comment]
Or try 2.2.6

**Comment by primitive-type** [comment]
@neumino That didn't change anything. I tried adding it on my own and then tried updating thinky (2.2.2 and rethinkdbdash 2.2.8), and in both cases the warning still appeared. I also get the warning frequently when using thinky's `pre` hooks, I've discovered. For now, since this is not a critical issue, I suppose I will just try turning off the Bluebird warnings entirely.
