### ISSUE TITLE
Unhandled rejection ReqlOpFailedError: Changefeed aborted (unavailable)

### ISSUE THREAD

**Issue by mbroadst** [neumino/rethinkdbdash#181]
I'm getting the following error in my tests when explicitly closing a change feed. I _think_ it's because a fetch was sent right before close was called, but I haven't had time to investigate further:

```
Unhandled rejection ReqlOpFailedError: Changefeed aborted (unavailable) in:
r.table("someTable").changes()
^^^^^^^^^^^^^^^^^^^^^^^^^^

    at Connection._processResponse (/Users/mbroadst/Development/redacted/node_modules/rethinkdbdash/lib/connection.js:229:19)
From previous event:
    at Cursor._fetch (/Users/mbroadst/Development/redacted/node_modules/rethinkdbdash/lib/cursor.js:114:11)
    at Cursor._push (/Users/mbroadst/Development/redacted/node_modules/rethinkdbdash/lib/cursor.js:135:86)
    at Connection._processResponse (/Users/mbroadst/Development/redacted/node_modules/rethinkdbdash/lib/connection.js:391:14)
    at Socket.<anonymous> (/Users/mbroadst/Development/redacted/node_modules/rethinkdbdash/lib/connection.js:150:14)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by neumino** [comment]
Are you running 2.2?

**Comment by mbroadst** [comment]
no this is still 2.1.17

I found the cause of the error from my side was actually that the path to explicitly close the change feed was not being called, so I think the actual root cause of this is a forced disconnect from the server and/or calling `dbDrop` on a table that has an existing change feed associated with it. Having said that, there still seemed no way for me to hook into catching this error

**Comment by neumino** [comment]
You need to bind an error listener/handler on the feed to catch this error.

**Comment by neumino** [comment]
```
feed.on('error', function(e) { })
// or
feed.next().then(...).error(...)
```

**Comment by mbroadst** [comment]
oh right, that makes sense. thanks!

**Comment by dvergeylen** [comment]
I am encountering the same problem. When I open a changefeed and (manually) delete the table it relies upon, the `ReqlOpFailedError` is making node to crash even when a `.error()` handler is bound and executed.

With the following code (`fetchNext` being the callback triggered when a new record arrives in the changefeed):

```javascript
cursor.next(fetchNext).error(function(err){
    console.log("Error spotted!");
    console.log(err.name);
});
```
give the following output:

```shell
Error spotted!
ReqlOpFailedError

/home/dv/project/src/backend/node_modules/rethinkdbdash/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^
ReqlOpFailedError: Changefeed aborted (unavailable) in:
r.table("activations").getAll(["1", "soutien"], {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    index: "game_id_categories"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).filter(function(var_2) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return var_2.hasFields("team_id")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).changes({
^^^^^^^^^^^^
    includeInitial: false,
    ^^^^^^^^^^^^^^^^^^^^^^
    includeStates: false,
    ^^^^^^^^^^^^^^^^^^^^^
    squash: 1
    ^^^^^^^^^
})
^^

    at Connection._processResponse /home/dv/project/src/backend/node_modules/rethinkdbdash/lib/connection.js:382:15)
    at Socket.<anonymous> (/home/dv/project/src/backend/node_modules/rethinkdbdash/lib/connection.js:201:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```

How could I prevent the error from being thrown (isn't that the purpose of catch? :confused: )?

**Comment by neumino** [comment]
@dvergeylen, please open a new issue and provide a script I can run. As far as I can tell, things are working as intended, the error is caught by your handler, so I'm not sure to understand the problem.
