### ISSUE TITLE
IndexCreate won't work anymore - Promise Issue

### ISSUE THREAD

**Issue by Chris-Cates** [neumino/rethinkdbdash#185]
```
Warning: a promise was created in a  handler but was not returned from it
    at Term.run (/Users/chriscates/projects/rydr/node_modules/rethinkdbdash/lib/term.js:145:15)
    at /Users/chriscates/projects/rydr/app.js:94:10
    at fn (/Users/chriscates/projects/rydr/node_modules/async/lib/async.js:741:34)
    at /Users/chriscates/projects/rydr/node_modules/async/lib/async.js:1208:16
    at /Users/chriscates/projects/rydr/node_modules/async/lib/async.js:166:37
    at /Users/chriscates/projects/rydr/node_modules/async/lib/async.js:701:43
    at /Users/chriscates/projects/rydr/node_modules/async/lib/async.js:167:37
    at /Users/chriscates/projects/rydr/node_modules/async/lib/async.js:1204:30
    at /Users/chriscates/projects/rydr/app.js:85:9
```

And the code
```
if (tableExists == false) {
      r.db('rydr').tableCreate('users')
        .run()
        .then(function(result) {
          finished(null, false);
        })
        .error(function(err) {
          finished(err);
        })
    } else {
      finished(null, true);
    }
```

**Comment by Chris-Cates** [comment]
Hmmm nevermind seems to be an issue with async.js

**Comment by neumino** [comment]
Can you provide a full script that produce this error. I'm not convinced that this is an issue in rethinkdbdash.

**Comment by neumino** [comment]
https://github.com/neumino/rethinkdbdash/issues/179 for reference.
