### ISSUE TITLE
Warning: a promise was created in a  handler but was not returned from it

### ISSUE THREAD

**Issue by meehow** [neumino/rethinkdbdash#193]
when rethinkdbdash is used together with [co](https://github.com/tj/co), it generates interesting warning
```
Warning: a promise was created in a  handler but was not returned from it
    at Term.run (/Users/michal/workspace/betty-crawler/node_modules/rethinkdbdash/lib/term.js:142:15)
    at Term.then (/Users/michal/workspace/betty-crawler/node_modules/rethinkdbdash/lib/term.js:2837:15)
From previous event:
    at Term.then (/Users/michal/workspace/betty-crawler/node_modules/rethinkdbdash/lib/term.js:2837:21)
    at next (/Users/michal/workspace/betty-crawler/node_modules/co/index.js:100:51)
    at onFulfilled (/Users/michal/workspace/betty-crawler/node_modules/co/index.js:69:7)
    at /Users/michal/workspace/betty-crawler/node_modules/co/index.js:54:5
    at co (/Users/michal/workspace/betty-crawler/node_modules/co/index.js:50:10)
    at Object.<anonymous> (/Users/michal/workspace/betty-crawler/lib/crawler.js:198:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
Interesting part is that it doesn't happen on first query, but in both cases [line 142 from term.js](https://github.com/neumino/rethinkdbdash/blob/master/lib/term.js#L142) is executed.

My super advanced code:
```javascript
var r = require('rethinkdbdash')();
require('co')(function* () {
  console.log(yield r.table('table').update({}));
  console.log(yield r.table('table').update({}));
}).catch(err => console.error(err.stack));
```

**Comment by neumino** [comment]
Do you still get the warning if you return a value after the second query?

**Comment by meehow** [comment]
Yes, there is a warning if I return something.
There is no warning if I comment out one of queries.

**Comment by meehow** [comment]
Looks like difference between these queries is in somewhere in `PoolMaster.prototype.getConnection` logic. First query goes to `self._line` and next queries are exiting from getConnection() in [line 117](https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L117).

**Comment by meehow** [comment]
This is new bluebird feature :)
http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it
it shows up only when env variable `BLUEBIRD_DEBUG=1` or `NODE_ENV=development`

**Comment by neumino** [comment]
This error happens with bluebird 3.0.5 and is not a `rethinkdbdash` issue.

This typically print a similar warning.
```
var Promise = require('bluebird');
require('co')(function* () {
  console.log(yield Promise.resolve('foo'));
  console.log(yield Promise.resolve('foo'));
}).catch(err => console.error(err.stack));
```

I just skimmed over `co` docs, but if I'm not mistaken, you are supposed to yield only once in your function.
