### ISSUE TITLE
Attaching an event handler to a cursor makes it loose every other item

### ISSUE THREAD

**Issue by niieani** [neumino/rethinkdbdash#209]
This was the weirdest debugging session, I was almost pulling my hairs out trying to figure out what's happening here. In the end I have found out that adding an event handler to a feed cursor makes the cursor behave weird. Example:

```js
r.table('test').changes().then((cursor) => {
  cursor.once('error', (err) => { console.log(err) });
  cursor.eachAsync(item => console.log(item));
  r.table('test').insert({ num: 1 }).then(()=>{});
  r.table('test').insert({ num: 2 }).then(()=>{});
  r.table('test').insert({ num: 3 }).then(()=>{});
  r.table('test').insert({ num: 4 }).then(()=>{});
});
```

The above will print out to the console `new_val` changes with items 2 and 4. 
Removing the line `cursor.once(...)` fixes the problem.
No error, no nothing.

**Comment by niieani** [comment]
OK, I found the culprit. It seems the problem is somewhere here: ([cursor.js](https://github.com/neumino/rethinkdbdash/blob/961853f0a4c61b635d82412bf8dbb23fca6798be/lib/cursor.js#L345)). 
Once I've commented out this part: 
```js
        setImmediate(function() {
          self._each(self._eachCb.bind(self), function() {
            if (self._emittedEnd === false) {
              self._emittedEnd = true;
              self._eventEmitter.emit('end');
            }
          });
```
Everything works fine.

**Comment by neumino** [comment]
Your script is throwing:
```
Unhandled rejection ReqlDriverError: You cannot call `eachAsync` once you have bound listeners on the Feed.
    at Cursor.eachAsync (/home/michel/projects/rethinkdb-all/rethinkdbdash/lib/cursor.js:308:11)
    at /home/michel/projects/rethinkdb-all/rethinkdbdash/test.js:4:10
    at tryCatcher (/home/michel/projects/rethinkdb-all/rethinkdbdash/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/michel/projects/rethinkdb-all/rethinkdbdash/node_modules/bluebird/js/release/promise.js:488:31)
    at Promise._settlePromise (/home/michel/projects/rethinkdb-all/rethinkdbdash/node_modules/bluebird/js/release/promise.js:545:18)
    at Promise._settlePromise0 (/home/michel/projects/rethinkdb-all/rethinkdbdash/node_modules/bluebird/js/release/promise.js:590:10)
    at Promise._settlePromises (/home/michel/projects/rethinkdb-all/rethinkdbdash/node_modules/bluebird/js/release/promise.js:673:18)
    at Async._drainQueue (/home/michel/projects/rethinkdb-all/rethinkdbdash/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/michel/projects/rethinkdb-all/rethinkdbdash/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/michel/projects/rethinkdb-all/rethinkdbdash/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

This is working as intended. You cannot mix both event emitter and `next`/`each`/etc.

Simply because if you do `on('data', console.log)`, the cursor will fetch data as fast as possible to emit the results. In this case we don't want to keep the results in a buffer in case you would like to call` next`/`each`.

If I'm not mistaken, the official driver behaves the same way.

**Comment by niieani** [comment]
Well I made a mistake with the example, the order of 'once' and `eachAsync` was incorrect.
```js
r.table('test').changes().then((cursor) => {
  cursor.eachAsync(item => console.log(item));
  cursor.once('error', (err) => { console.log(err) });
  r.table('test').insert({ num: 1 }).then(()=>{});
  r.table('test').insert({ num: 2 }).then(()=>{});
  r.table('test').insert({ num: 3 }).then(()=>{});
  r.table('test').insert({ num: 4 }).then(()=>{});
});
```
This code should execute to prove what I meant. Even if what you say is true, in that you can't have both an emitter and use `eachAsync` or `each`, there should be an error thrown when trying to use an emitter after one of the `each` or other commands were used. Otherwise unexpected behavior happens as I described above (loosing every 2nd item) and the developer is left to get to the bottom of this problem on his own.

**Comment by neumino** [comment]
Hum, you are supposed to bind the listener for errors before calling `each`/`eachAsync`. if you don't you could emit an error before the listener is bound which eventually crash your process.

We could add some safety though. You're welcome to send a pull request.
