### ISSUE TITLE
ECONNRESET, Unhandled 'error' event

### ISSUE THREAD

**Issue by tomcheung789** [neumino/rethinkdbdash#234]
I am trying to simulate a database failure with this code.
```
'use strict';

const config = {
  db: 'jo',
  servers: [{
    host: '192.168.125.120',
    port: 28015
  }]
};
const r = require('rethinkdbdash')(config);

r.getPoolMaster().on('healthy', (healthy) => {
  console.log(`[db] healthy changes ${healthy}`);
});
```
When I shutdown the rethinkdb server, the node instance crashed immediately with the following error, instead of trying to reconnect the server.
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at TCP.onread (net.js:552:26)
```

If I changed the driver file **connection.js** line 97 from
`self.emit('error', error);`
to
`reject(new Err.ReqlDriverError('Failed to connect to '+self.host+':'+self.port+'\nFull error:\n'+JSON.stringify(error)).setOperational());`

The problem just gone.

Testing environment:

- Client: on OSX, nodejs 5.10.0 , rethinkdbdash 2.2.18
- Server: on Linux, rethinkdb 2.2.6

**Comment by neumino** [comment]
Hum, I have a hard time reproducing that on my linux machine.
What happens maybe is that the connection is closed, and then emit this error?

Can you try to see if the `end` or `close` event is emitted on the connection before it emits `ECONNRESET`?

**Comment by tomcheung789** [comment]
The `end` event is emitted before `ECONNRESET`

```
[connection on end]
[self on end]
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at TCP.onread (net.js:552:26)
```

**Comment by neumino** [comment]
Hum, looking at the docs, `end` is emitted only when a FIN packet is received, so removing the listeners should be done on `close`.
I'll send a fix in a minutes.

**Comment by lbguilherme** [comment]
This problem still happens on the latest release. A RethinkDB shutdown caused ECONNRESET, which crashed the Node process.

```
... a lot of unrelated logs ...
Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
```

Then the process dies.

**Comment by panpansh** [comment]
Same error but fixed handling process uncaughtException matching rethinkdb then restart connection

```js
const process = require('process');
process.on('uncaughtException', async (err) => {
    const { sleep } = require('../utils/misc');
    if (err.stack.includes('rethinkdb')) {
        console.log(err.stack);
        await sleep(10000);
        this.init();
    }
});

// here is the sleep function :
exports.sleep = (ms) => {
    return new Promise(resolve => setTimeout(resolve, ms));
}
```

**Comment by panpansh** [comment]
Same error but fixed handling process uncaughtException matching rethinkdb then restart connection

```js
const process = require('process');
const { sleep } = require('../utils/misc');
process.on('uncaughtException', async (err) => {
    // console.log(err.stack);
    if (err.stack.includes('rethinkdb')) {
        await sleep(10000);
        this.init();
    }
});

exports.rethink_conn = null;

const r = require('rethinkdb');
exports.init = (host = '192.168.1.41', port = 28015, db_name = 'mybestdbeverseen') => {
    r.connect({ host: host, port: port }, (err, conn) => {
        if (err) throw err;
        r.dbList().contains(db_name)
            .do((databaseExists) => {
                return r.branch(
                    databaseExists,
                    { dbs_created: 0 },
                    r.dbCreate(db_name)
                );
            }).run(conn, (err, res) => {
                if (err) throw err;
                // console.log(res);
                conn.use(db_name);
                this.rethink_conn = conn;
            });

    });
}

// here is the sleep function from my misc file :
exports.sleep = (ms) => {
    return new Promise(resolve => setTimeout(resolve, ms));
}
```
