### ISSUE TITLE
TypeError: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by deoqc** [neumino/rethinkdbdash#239]
The following error started to pop, crashing the server.
I don't have a clue how to reproduce it, 'cause and did't see it coming also. 
Any help appreciated.

[Error] TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:140:11)
    at new Buffer (buffer.js:62:10)
    at Socket.<anonymous> (.../app/node_modules/rethinkdbdash/lib/connection.js:113:22)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:10)

**Comment by roblav96** [comment]
Same error here. Reverting to 2.2.18 fixed this issue for me.

**Comment by deoqc** [comment]
Than's, tilde semver fooled me.

**Comment by marshall007** [comment]
Duplicate of #238.
