### ISSUE TITLE
Documentation for .changes.run() call

### ISSUE THREAD

**Issue by thomasmodeneis** [neumino/rethinkdbdash#259]
Hi,

I can't find any docs on readme.md file about running changes calls together with socket.io updates, and right now it seems that no matter what I try it always end up with this warn:

```
[0] Warning: a promise was created in a handler but was not returned from it
[0]     at Cursor._next (/opt/test/node_modules/rethinkdbdash/lib/cursor.js:54:10)
[0]     at Cursor._each (/opt/test/node_modules/rethinkdbdash/lib/cursor.js:252:8)
[0]     at crud.js:22:16
[0]     at processImmediate [as _immediateCallback] (timers.js:383:17)
[0] From previous event:
[0]     at Object.liveUpdates (crud.js:20:26)
[0]     at Object.<anonymous> (server.js:45:13)
[0]     at Module._compile (module.js:413:34)
[0]     at loader (/opt/test/node_modules/babel-register/lib/node.js:158:5)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/opt/test/node_modules/babel-register/lib/node.js:168:7)
[0]     at Module.load (module.js:357:32)
[0]     at Function.Module._load (module.js:314:12)
[0]     at Module.require (module.js:367:17)
[0]     at require (internal/module.js:16:19)
[0]     at Object.<anonymous> (/opt/test/server.babel.js:3:1)
[0]     at Module._compile (module.js:413:34)
[0]     at Object.Module._extensions..js (module.js:422:10)
[0]     at Module.load (module.js:357:32)
[0]     at Function.Module._load (module.js:314:12)
[0]     at Function.Module.runMain (module.js:447:10)
[0]     at startup (node.js:140:18)
[0]     at node.js:1001:3
```

Code:
```
r
        .table('feed')
        .changes().run().then(function (feed) {
        console.log('Listening for changes...');
        feed.each((err, change) => {
            console.log('Change detected', change);
            io.emit('feed-change', change);
        });
    });
```

Any ideas where is the related doc for performing such call or any hints on how-to avoid warns ?

Cheers.

**Comment by neumino** [comment]
Add a return null in your `then` handler. This is a bluebird warning.

http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

**Comment by thomasmodeneis** [comment]
That works, thanks.

**Comment by webmutation** [comment]
This helped, the way to handle changes() should have an example in the readme :)
It seems to be the one case where you have to handle the result, since all others are returned in Array.
