### ISSUE TITLE
`replace` seems to be NOP that always succeeds now, have to use `insert(..., { conflict: 'replace' })` now.

### ISSUE THREAD

**Issue by ohjames** [neumino/rethinkdbdash#311]
On another system running rethinkdb 2.3.1 `replace` works fine, after upgrading rethinkdb to `2.3.5` the replace call returns a promise that succeeds, but when we check the DB it hasn't replaced (or inserted) any documents and is unable to.

**Comment by neumino** [comment]
Can you provide a script where we can reproduce this issue?

**Comment by viridia** [comment]
I'm seeing something very similar. My code looks like this:

    this.r.db(process.env.DB_NAME).table('Recipes').insert(recipe).then((result: any) => {
      // etc.
    });

This works fine on my ubuntu laptop, but on my macbook the insert doesn't throw an error but doesn't insert anything either.

**Comment by viridia** [comment]
Also, out of curiousity I checked out the package and ran the unit tests on my macbook, got the following errors:

790 passing (4m)
  7 failing

```
  1)  `server` should work:

      AssertionError: false == true
      + expected - actual

      -false
      +true

      at test/accessing-reql.js:362:5
      at Generator.next (<anonymous>)
      at Generator.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  2)  Updating data to make it heavier:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  3)  pipe should work with a writable stream - 200-200:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  4)  pipe should work with a writable stream - 200-20:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  5)  pipe should work with a writable stream - 20-200:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  6)  pipe should work with a writable stream - 50-50:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  7)  toStream((writable: true}) should handle options:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Note however this may be a problem in my setup - I'm using a rethinkdb instance that's in a docker container inside a kubernetes cluster.
