### ISSUE TITLE
Disabling pooling in rethinkdbdash

### ISSUE THREAD

**Issue by asteranup** [neumino/rethinkdbdash#314]
Hi There,

I was trying to disable pooling. But it breaks saying "`run` was called without a connection and no pool has been created". Code is very simple-

```
var r = require('rethinkdbdash')({
    pool: false,
    cursor: true,
    host: 'xx.xx.xx.xx,
    port: 28015,
    db:'brief-prod'
});

r.table('users').run().then(function(cursor) {
  cursor.toArray().then(function(result) {
    console.log(result);
  });
});
```

Not sure what am I missing. Stack is as follows-

D:\POCs\NodePOCs\rethinkdbdash\node_modules\rethinkdbdash\lib\term.js:124
      throw new Error.ReqlDriverError('`run` was called without a connection and no pool has been created', self._query);
      ^
ReqlDriverError: `run` was called without a connection and no pool has been created after:
r.table("users")
    at Term.run (D:\POCs\NodePOCs\rethinkdbdash\node_modules\rethinkdbdash\lib\term.js:124:13)
    at Object.<anonymous> (D:\POCs\NodePOCs\rethinkdbdash\server.js:9:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:575:10)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)

Thanks
Anup

**Comment by neumino** [comment]
If you don't use a pool, you have to manually create connections with r.connect

**Comment by asteranup** [comment]
Can you please direct me any sample for this. I could not find any example for the same.

**Comment by neumino** [comment]
https://github.com/neumino/rethinkdbdash/blob/master/test/accessing-reql.js
