### ISSUE TITLE
Cant get a Pool in State healthy again

### ISSUE THREAD

**Issue by ralf-walk** [neumino/rethinkdbdash#324]
Hello,

we have an issue regarding the Pool Handling - an unhealthy Pool wont become healthy again.

The issue is reproducible as follows:

1. one nodejs service connects to the rethinkdb
2. rethinkdb gets killed
3. the nodejs app still tries to execute queries until the pool is not considered healty anymore
4. rethinkdb is back again
5. there is no chance of the pool to become healthy again
```

Error message:
2017-02-03-12:50:15 0|registry | [2017-02-03 12:50:15.938] [ERROR] default - router.post: POST /: error in catch(): { ReqlDriverError: None of the pools have an opened connection and failed to open a new one.
2017-02-03-12:50:15 0|registry |     at /service/node_modules/rethinkdbdash/lib/pool_master.js:127:14
2017-02-03-12:50:15 0|registry |     at Promise._execute (/service/node_modules/rethinkdbdash/node_modules/bluebird/js/release/debuggability.js:300:9)
2017-02-03-12:50:15 0|registry |     at Promise._resolveFromExecutor (/service/node_modules/rethinkdbdash/node_modules/bluebird/js/release/promise.js:481:18)
2017-02-03-12:50:15 0|registry |     at new Promise (/service/node_modules/rethinkdbdash/node_modules/bluebird/js/release/promise.js:77:14)
2017-02-03-12:50:15 0|registry |     at PoolMaster.getConnection (/service/node_modules/rethinkdbdash/lib/pool_master.js:126:12)
2017-02-03-12:50:15 0|registry |     at /service/node_modules/rethinkdbdash/lib/term.js:143:20
2017-02-03-12:50:15 0|registry |     at Promise._execute (/service/node_modules/rethinkdbdash/node_modules/bluebird/js/release/debuggability.js:300:9)
2017-02-03-12:50:15 0|registry |     at Promise._resolveFromExecutor (/service/node_modules/rethinkdbdash/node_modules/bluebird/js/release/promise.js:481:18)
2017-02-03-12:50:15 0|registry |     at new Promise (/service/node_modules/rethinkdbdash/node_modules/bluebird/js/release/promise.js:77:14)
2017-02-03-12:50:15 0|registry |     at Term.run (/service/node_modules/rethinkdbdash/lib/term.js:142:15)
2017-02-03-12:50:15 0|registry |     at Term.then (/service/node_modules/rethinkdbdash/lib/term.js:2876:15)
2017-02-03-12:50:15 0|registry |     at Object.handle (/service/server.js:76:6)
2017-02-03-12:50:15 0|registry |     at next_layer (/service/node_modules/express/lib/router/route.js:103:13)
2017-02-03-12:50:15 0|registry |     at Route.dispatch (/service/node_modules/express/lib/router/route.js:107:5)
2017-02-03-12:50:15 0|registry |     at /service/node_modules/express/lib/router/index.js:195:24
2017-02-03-12:50:15 0|registry |     at Function.proto.process_params (/service/node_modules/express/lib/router/index.js:251:12)
2017-02-03-12:50:15 0|registry |     at next (/service/node_modules/express/lib/router/index.js:189:19)
2017-02-03-12:50:15 0|registry |     at next_layer (/service/node_modules/express/lib/router/route.js:77:14)
2017-02-03-12:50:15 0|registry |     at next_layer (/service/node_modules/express/lib/router/route.js:81:14)
2017-02-03-12:50:15 0|registry |     at Route.dispatch (/service/node_modules/express/lib/router/route.js:107:5)
2017-02-03-12:50:15 0|registry |     at /service/node_modules/express/lib/router/index.js:195:24
2017-02-03-12:50:15 0|registry |     at Function.proto.process_params (/service/node_modules/express/lib/router/index.js:251:12)
2017-02-03-12:50:15 0|registry |   msg: 'None of the pools have an opened connection and failed to open a new one',
2017-02-03-12:50:15 0|registry |   message: 'None of the pools have an opened connection and failed to open a new one.',
2017-02-03-12:50:15 0|registry |   isOperational: true }
```

 Could you please help us? Setting the option pool: false is no options to us as we use thinky which as far as we see depends on connection pooling.

**Comment by neumino** [comment]
The pool automatically reconnects. The pool doesn't try to reconnect with an exponential fallback. You probably just want to tweak the options in your case
https://github.com/neumino/rethinkdbdash#importing-the-driver

**Comment by Glathrop** [comment]
@neumino are these configuration options available in thinky as well?  We've been battling this issue for quite some time and I cannot seem to find a consistent information on exactly where to look. It seems like ping option here could help keep the connection alive. Thinky uses rethinkdbdash under the hood correct? Time to simply ditch thinky? @hantho @chippawa
