### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ghost** [neumino/rethinkdbdash#331]
The handling of async loops should use `setTimeout(loop, 0);` to allow V8 to clear the stack once in a while.

```RangeError: Maximum call stack size exceeded
    at Function.Term.expr (/root/edom/node_modules/rethinkdbdash/lib/term.js:2333:18)
    at /root/edom/node_modules/rethinkdbdash/lib/term.js:2362:40
    at Object.loopKeys (/root/edom/node_modules/rethinkdbdash/lib/helper.js:56:14)
    at Function.Term.expr (/root/edom/node_modules/rethinkdbdash/lib/term.js:2360:12)
    at /root/edom/node_modules/rethinkdbdash/lib/term.js:2362:40
    at Object.loopKeys (/root/edom/node_modules/rethinkdbdash/lib/helper.js:56:14)
    at Function.Term.expr (/root/edom/node_modules/rethinkdbdash/lib/term.js:2360:12)
    at /root/edom/node_modules/rethinkdbdash/lib/term.js:2362:40
    at Object.loopKeys (/root/edom/node_modules/rethinkdbdash/lib/helper.js:56:14)
    at Function.Term.expr (/root/edom/node_modules/rethinkdbdash/lib/term.js:2360:12)
    at Function.Term.expr (/root/edom/node_modules/rethinkdbdash/lib/term.js:2348:35)
    at /root/edom/node_modules/rethinkdbdash/lib/term.js:2362:40
    at Object.loopKeys (/root/edom/node_modules/rethinkdbdash/lib/helper.js:56:14)
    at Function.Term.expr (/root/edom/node_modules/rethinkdbdash/lib/term.js:2360:12)
    at /root/edom/node_modules/rethinkdbdash/lib/term.js:2362:40
    at Object.loopKeys (/root/edom/node_modules/rethinkdbdash/lib/helper.js:56:14)
    at Function.Term.expr (/root/edom/node_modules/rethinkdbdash/lib/term.js:2360:12)```

**Comment by neumino** [comment]
What query did you use? Didn't you write a object with thousands of nested
levels?

**Comment by chakravarthysm** [comment]
+1

**Comment by chakravarthysm** [comment]
Query Used -  const query = this.r.table('Documents').get(id)
      .merge((doc) => {
        let mergeQuery = this.r.table('Versions').getAll(doc('id'), {
          index: 'document_id',
        });
        mergeQuery = mergeQuery.orderBy(this.r.desc('version')).limit(1);
        mergeQuery = mergeQuery.eqJoin('data_id', this.r.table('Data'))
          .without({
            right: 'id',
            left: ['data_id', 'id', 'document'],
          })
          .zip()
          .max();

        return {
          requested_version: mergeQuery,
        };
      });
    this.log.trace(`RethinkStorage.get: Fetching clip for ${id}`);
    query.run()
      .then((result) => {
        callback(null, this.transformOutput(result));
      })
      .catch(err => callback(err));
