### ISSUE TITLE
Error while trying to patch multiple records

### ISSUE THREAD

**Issue by VMois** [neumino/rethinkdbdash#342]
### Steps to reproduce
Trying to patch using following code (hook it's variable from), according to https://legacy.docs.feathersjs.com/services/readme documentation:
```
const params = {
      query: {
              page_id: hook.result.id
          }
      }
      hook.app.service('/files').patch(null, { deleted: true }, params)
      .then(() => resolve(hook))
      .catch((err) => {
        hook.app.get('sentryClient').captureException(err);
        reject({});
      });
```
### Expected behavior
set deleted: true to all records in database where page_id is equal hook.result.id 

### Actual behavior
Error:
```
{ ReqlRuntimeError: Primary keys must be either a number, string, bool, pseudotype or array (got type NULL):
null in:
r.db("database").table("layouts").get(null).update({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    deleted: true
    ^^^^^^^^^^^^^
}, {
^^^^
    returnChanges: true
    ^^^^^^^^^^^^^^^^^^^
})
^^

    at Connection._processResponse (/home/vmois/projects/test/node_modules/rethinkdbdash/lib/connection.js:395:15)
    at Socket.<anonymous> (/home/vmois/projects/test/node_modules/rethinkdbdash/lib/connection.js:201:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
From previous event:
    at Function.Term.run (/home/vmois/projects/test/node_modules/rethinkdbdash/lib/term.js:142:15)
    at /home/vmois/projects/test/node_modules/feathers-rethinkdb/lib/index.js:280:44
    at process._tickCallback (internal/process/next_tick.js:109:7)
  msg: 'Primary keys must be either a number, string, bool, pseudotype or array (got type NULL):\nnull',
  message: 'Primary keys must be either a number, string, bool, pseudotype or array (got type NULL):\nnull in:\nr.db("database").table("layouts").get(null).update({\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    deleted: true\n    ^^^^^^^^^^^^^\n}, {\n^^^^\n    returnChanges: true\n    ^^^^^^^^^^^^^^^^^^^\n})\n^^\n',
  frames: [] }
{}

```

It's a bug or my fail? Thank you.

**Module versions** (especially the part that's not working): feathers 2.1.7, feathers-rethinkdb 0.4.3, rethinkdbdash 2.3.29

**NodeJS version**: 7.10.1

**Operating System**: Debian 8

**Comment by aleclarson** [comment]
This is an issue with `feathers-rethinkdb`.
You can't call `table.get(null).update()`.
You need to call `table.update()` instead.

My guess is that [these lines](https://github.com/feathersjs/feathers-rethinkdb/blob/master/src/index.js#L206-L210) should be changed to:

```js
if (Array.isArray(getData)) {
  query = this.table.getAll(...getData.map(item => item[this.id]));
} else if (id !== null && id !== undefined) {
  query = this.table.get(id);
}
```

**Comment by neumino** [comment]
Indeed that's an issue in the feather module not rethinkdbdash
