### ISSUE TITLE
None of the pools have an opened connection and failed to open a new one.

### ISSUE THREAD

**Issue by Zorotic** [neumino/rethinkdbdash#379]
I've currently using enmap for a wrapper, I get this when trying to connect to the database. 
I'm using the docker instance of Rethink. 
These are the ports rethink is running on:
```
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
```
NOTE: I'm able to connect to the web interface for it, and no logs of attempted connections are being logged there

Error: 
```
ReqlDriverError: None of the pools have an opened connection and failed to open a new one.
    at PoolMaster._flushErrors (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/rethinkdbdash/lib/pool_master.js:104:31)
    at Pool.<anonymous> (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/rethinkdbdash/lib/pool_master.js:450:12)
    at Pool.emit (events.js:182:13)
    at Pool._decreaseNumConnections (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/rethinkdbdash/lib/pool.js:118:10)
    at /home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/rethinkdbdash/lib/pool.js:291:10
    at tryCatcher (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/catch_filter.js:24:41
    at tryCatcher (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/zoro/Desktop/Maya-Core/Maya-ERIS/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
```

**Comment by ssribeiro** [comment]
same here

**Comment by rriixx** [comment]
+1

**Comment by kmashiki** [comment]
+1

**Comment by fluse** [comment]
+1
