### ISSUE TITLE
Object mode for streaming

### ISSUE THREAD

**Issue by adius** [neumino/rethinkdbdash#76]
Currently I get following error when piping from rethinkdb to express.js response:

```log
Unhandled rejection TypeError: first argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:433:11)
    at ReadableStream.ondata (_stream_readable.js:540:20)
    at ReadableStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at ReadableStream.Readable.push (_stream_readable.js:126:10)
    at /Users/adrian/Projects/CityViz/CityViz/node_modules/rethinkdbdash/lib/stream.js:112:26
    at tryCatcher (/Users/adrian/Projects/CityViz/CityViz/node_modules/rethinkdbdash/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/adrian/Projects/CityViz/CityViz/node_modules/rethinkdbdash/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/adrian/Projects/CityViz/CityViz/node_modules/rethinkdbdash/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/Users/adrian/Projects/CityViz/CityViz/node_modules/rethinkdbdash/node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (/Users/adrian/Projects/CityViz/CityViz/node_modules/rethinkdbdash/node_modules/bluebird/js/main/async.js:84:12)
    at Async._drainQueues (/Users/adrian/Projects/CityViz/CityViz/node_modules/rethinkdbdash/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/adrian/Projects/CityViz/CityViz/node_modules/rethinkdbdash/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:355:11)
```

A workaround is to change https://github.com/neumino/rethinkdbdash/blob/master/lib/stream.js#L66 and https://github.com/neumino/rethinkdbdash/blob/master/lib/stream.js#L112 to `self.push(JSON.stringify(data))`

The correct way to fix this would be to properly use the object mode of streams!

**Comment by neumino** [comment]
That's because you are not supposed to directly pipe to express.

Rethinkdbdash creates streams in `objectMode: true`. If you pipe it to express, it will be switched to `objectMode: false` as the response is a writable streams in mode `objectMode: false`.
You need to pipe it to a transform stream that will stringify the output first.

Quick example:
```
var r = require('.rethinkdbdash')();

var express = require('express')
var app = express()

var Stringify = require('streaming-json-stringify');
Stringify.prototype.open = new Buffer('', 'utf8')
Stringify.prototype.seperator = new Buffer('\n', 'utf8')
Stringify.prototype.close = new Buffer('', 'utf8')

app.get('/', function (req, res) {
  r.db('test').table('test').toStream()
    .pipe(Stringify())
    .pipe(res);
})

var server = app.listen(3000, function () {
  console.log('Server started')
})
```

**Comment by marshall007** [comment]
See also [`dominictarr/JSONStream`](https://github.com/dominictarr/JSONStream) as an alternative to `streaming-json-stringify`. It supports streaming `JSON.parse()` as well.

**Comment by neumino** [comment]
https://github.com/dominictarr/JSONStream looks nice. Thanks @marshall007 for the info :)

**Comment by adius** [comment]
Thanks for clarification. Works like a charm =)
